### ISSUE TITLE
Fix rollup namedExport relative pathing wrt. root level

### ISSUE THREAD

**Issue by jay-almaraz** [NikChao/coffee-shope#14]
Changing `package_dir` in `baristarc` affects the relative path of the root node_modules directory, and therefore things inside of any created components/utils must take this into account when generating relative paths.

e.g. in Campfire:
In the `rollup.config.js` file the `'../../node_modules/react/index.js': reactExports` line does not go up enough levels to reach the project root, as it was hardcoded with the intention of the `components` directory being at the project root.
```js
// packages/components/button/rollup.config.js
  ...
      namedExports: {
        'node_modules/react/index.js': reactExports,
        // just in case its pulling deps from root of mono-repo
        '../../node_modules/react/index.js': reactExports
      }
  ...
```
Should be:
```js
// packages/components/button/rollup.config.js
     namedExports: {
        ...
        // just in case its pulling deps from root of mono-repo
        '../../../node_modules/react/index.js': reactExports
      }
```

**Comment by NikChao** [comment]
yeah, good point, this was a hack for our current component library, will look into it.

**Comment by NikChao** [comment]
Fixed with regex for node_modules
